### ISSUE TITLE
More obvious package name

### ISSUE THREAD

**Issue by mateja176** [UlisesGascon/browser-redirect#2]
Thanks for the blog post! However, I was wondering why go for a more descriptive name for the package like `browser-redirect-do-not-install` or `browser-redirect-malicious-example`, to significantly reduce the chances of unwanted installs and free the name space? Similarly to how `dangerouslySetInnerHTML` is intentionally verbose and obvious.

**Comment by UlisesGascon** [comment]
Thanks for the feedback @mateja176! :-)

I wish I could but the only option [I have is using `deprecate`](https://stackoverflow.com/questions/28371669/renaming-a-published-npm-module), but even then the package still available. The evil payload is commented in the published version. 

So there is no real risk for anybody even if they install it by mistake.
